type Tweet {
	author: String!
	timestamp: Time!
	text: String!
	likes: [String!]
	replyingTo: String
	replies: [String!]
}

type User {
	name: String!
	avatarURL: String!
	tweets: [String!]
}

type Mutation {
	saveLikeToggle(id: ID!, hasLiked: Boolean!, authedUser: ID!): Tweet!
}

type Query {
	allTweets: [Tweet!]
	allUsers: [User!]
}
